#!/bin/bash

# Crear carpeta Tor en el Escritorio
mkdir -p ~/Escritorio/Tor

# Moverse a la carpeta creada
cd ~/Escritorio/Tor

# Descargar el archivo de Tor Browser
wget https://www.torproject.org/dist/torbrowser/13.5.1/tor-browser-linux-x86_64-13.5.1.tar.xz

# Descomprimir el archivo descargado
tar -xvf tor-browser-linux-x86_64-13.5.1.tar.xz

# Borrar el archivo comprimido descargado
rm tor-browser-linux-x86_64-13.5.1.tar.xz

echo "Tor Browser ha sido instalado correctamente"

