#!/bin/bash

# Verifica si el usuario tiene permisos de sudo
if ! sudo -v; then
    echo "El usuario no tiene permisos de sudo. Por favor, asegúrate de tener permisos para instalar paquetes."
    exit 1
fi

# Actualiza la lista de paquetes y asegúrate de tener los repositorios más recientes
sudo apt update

# Instala las dependencias necesarias para la construcción y ejecución de Recon-NG
sudo apt install -y build-essential git python3 python3-pip python3-venv

# Define el directorio de destino
DEST_DIR="/home/$USER/Escritorio/Recon-NG"

# Crea el directorio de destino si no existe y establece los permisos adecuados
mkdir -p "$DEST_DIR"
chmod 755 "$DEST_DIR"

# Clona el repositorio de Recon-NG desde GitHub en el directorio del usuario
git clone https://github.com/lanmaster53/recon-ng.git "$DEST_DIR"

# Cambia al directorio de Recon-NG
cd "$DEST_DIR"

# Crea un entorno virtual para Python y actívalo
python3 -m venv venv
source venv/bin/activate

# Instala las dependencias de Python para Recon-NG desde el archivo requirements.txt
pip install -r requirements.txt

# Ejecuta Recon-NG
./recon-ng
