#!/bin/bash

# Comprobar si se está ejecutando como root
if [[ $EUID -ne 0 ]]; then
   echo "Este script debe ejecutarse como root" 
   exit 1
fi

# Obtener el nombre del usuario actual
USER=$(logname)

# Definir el directorio
DIRECTORIO="/home/$USER/Escritorio/Recon-NG"

# Moverse al directorio creado por el usuario
cd $DIRECTORIO

# Instalar dependencias necesarias
echo "Instalando dependencias necesarias..."
apt-get update -y
apt-get install -y git python3 python3-pip python3-venv

# Clonar el repositorio de Recon-NG
echo "Clonando el repositorio de Recon-NG en $DIRECTORIO..."
git clone https://github.com/lanmaster53/recon-ng.git

# Cambiar al directorio de Recon-NG
cd recon-ng

# Crear y activar un entorno virtual
echo "Creando y activando el entorno virtual..."
python3 -m venv venv
source venv/bin/activate

# Instalar las dependencias de Python
echo "Instalando dependencias de Python..."
pip install -r REQUIREMENTS

# Crear enlace simbólico para facilitar la ejecución de Recon-NG
echo "Creando enlace simbólico para Recon-NG..."
ln -s $DIRECTORIO/recon-ng/recon-ng /usr/local/bin/recon-ng

echo "Instalación de Recon-NG completada. Puedes ejecutarlo con el comando 'recon-ng'."
